// Code generated by go generate ./character; DO NOT EDIT.

package character

import (
	"xqdj/character/doppel"
	"xqdj/character/glitch"
	"xqdj/character/knight"
	"xqdj/character/melee"
	"xqdj/character/menreiki"
	"xqdj/character/ranged"
	"xqdj/character/twin"
	"xqdj/character/waller"
	"xqdj/character/warden"
)

const (
	KindDoppel      = 分身者.KindDoppel
	KindGlitch      = 地慧星.KindGlitch
	KindGlitchGhost = 地慧星.KindGlitchGhost
	KindGlitchSlash = 地慧星.KindGlitchSlash
	KindKnight      = 小骑士.KindKnight
	KindMelee       = 原型机_近战.KindMelee
	KindMenreiki    = 面灵气.KindMenreiki
	KindRanged      = 原型机_远程.KindRanged
	KindTwin        = 无下限术士.KindTwin
	KindWaller      = 筑墙者.KindWaller
	KindWarden      = 盾士.KindWarden
)
