// Code generated by go generate ./character; DO NOT EDIT.

package character

import (
	"xqdj/character/doppel"
	"xqdj/character/engine"
	"xqdj/character/fisher"
	"xqdj/character/glitch"
	"xqdj/character/knight"
	"xqdj/character/melee"
	"xqdj/character/menreiki"
	"xqdj/character/prisoner"
	"xqdj/character/radar"
	"xqdj/character/ranged"
	"xqdj/character/reaper"
	"xqdj/character/twin"
	"xqdj/character/udongein"
	"xqdj/character/waller"
	"xqdj/character/warden"
	"xqdj/character/wolf"
)

const (
	KindClone       = 分身者.KindClone
	KindCloneArc    = 分身者.KindCloneArc
	KindDoppel      = 分身者.KindDoppel
	KindEngine      = 内燃机.KindEngine
	KindFish        = 钓鱼佬.KindFish
	KindFishBig     = 钓鱼佬.KindFishBig
	KindFishMid     = 钓鱼佬.KindFishMid
	KindFisher      = 钓鱼佬.KindFisher
	KindFlood       = 钓鱼佬.KindFlood
	KindPond        = 钓鱼佬.KindPond
	KindGlitch      = 地慧星.KindGlitch
	KindGlitchArc   = 地慧星.KindGlitchArc
	KindGlitchGhost = 地慧星.KindGlitchGhost
	KindGlitchShot  = 地慧星.KindGlitchShot
	KindGlitchSlash = 地慧星.KindGlitchSlash
	KindKnight      = 小骑士.KindKnight
	KindKnightArc   = 小骑士.KindKnightArc
	KindMelee       = 原型机_近战.KindMelee
	KindMeleeArc    = 原型机_近战.KindMeleeArc
	KindMenreiki    = 面灵气.KindMenreiki
	KindMenreikiArc = 面灵气.KindMenreikiArc
	KindCage        = 囚徒.KindCage
	KindChair       = 囚徒.KindChair
	KindGallows     = 囚徒.KindGallows
	KindHook        = 囚徒.KindHook
	KindPrisoner    = 囚徒.KindPrisoner
	KindRadar       = 雷达.KindRadar
	KindRanged      = 原型机_远程.KindRanged
	KindReap        = 收割者.KindReap
	KindReaper      = 收割者.KindReaper
	KindSickle      = 收割者.KindSickle
	KindTwin        = 无下限术士.KindTwin
	KindTwinArc     = 无下限术士.KindTwinArc
	KindTwinBlueArc = 无下限术士.KindTwinBlueArc
	KindAspect      = 优昙华院.KindAspect
	KindAspectShot  = 优昙华院.KindAspectShot
	KindBlast       = 优昙华院.KindBlast
	KindCrown       = 优昙华院.KindCrown
	KindGas         = 优昙华院.KindGas
	KindLaser       = 优昙华院.KindLaser
	KindMindShard   = 优昙华院.KindMindShard
	KindMindShot    = 优昙华院.KindMindShot
	KindSeekShot    = 优昙华院.KindSeekShot
	KindUdongein    = 优昙华院.KindUdongein
	KindWaller      = 筑墙者.KindWaller
	KindWarden      = 盾士.KindWarden
	KindMoon        = 狼人.KindMoon
	KindWolf        = 狼人.KindWolf
	KindWolfArc     = 狼人.KindWolfArc
	KindWolfBite    = 狼人.KindWolfBite
)
