//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const modulePath = "xqdj/character"

func main() {
	src, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	formatted, err := format.Source(src)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile("all.go", formatted, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

type pack struct {
	dir  string
	name string
	kind []kindConst
}

type kindConst struct {
	ident string
	value string
}

func generate() ([]byte, error) {
	packs, err := scanPacks(".")
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by go generate ./character; DO NOT EDIT.\n\n")
	b.WriteString("package character\n\n")
	if len(packs) == 0 {
		return b.Bytes(), nil
	}
	b.WriteString("import (\n")
	for _, p := range packs {
		fmt.Fprintf(&b, "\t%q\n", modulePath+"/"+p.dir)
	}
	b.WriteString(")\n\n")
	b.WriteString("const (\n")
	for _, p := range packs {
		for _, k := range p.kind {
			fmt.Fprintf(&b, "\t%s = %s.%s\n", k.ident, p.name, k.ident)
		}
	}
	b.WriteString(")\n")
	return b.Bytes(), nil
}

func scanPacks(root string) ([]pack, error) {
	ents, err := os.ReadDir(root)
	if err != nil {
		return nil, err
	}
	var dirs []string
	for _, e := range ents {
		if !e.IsDir() || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		ok, err := hasGo(filepath.Join(root, e.Name()))
		if err != nil {
			return nil, err
		}
		if ok {
			dirs = append(dirs, e.Name())
		}
	}
	sort.Strings(dirs)
	out := make([]pack, 0, len(dirs))
	for _, dir := range dirs {
		p, err := parsePack(filepath.Join(root, dir), dir)
		if err != nil {
			return nil, err
		}
		out = append(out, p)
	}
	return out, nil
}

func hasGo(dir string) (bool, error) {
	ents, err := os.ReadDir(dir)
	if err != nil {
		return false, err
	}
	for _, e := range ents {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") && !strings.HasSuffix(e.Name(), "_test.go") {
			return true, nil
		}
	}
	return false, nil
}

func parsePack(dir, folder string) (pack, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(info os.FileInfo) bool {
		name := info.Name()
		return strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")
	}, 0)
	if err != nil {
		return pack{}, err
	}
	if len(pkgs) != 1 {
		return pack{}, fmt.Errorf("%s: want 1 package, got %d", folder, len(pkgs))
	}
	var p pack
	p.dir = folder
	seen := map[string]bool{}
	for _, pkg := range pkgs {
		p.name = pkg.Name
		for _, f := range pkg.Files {
			ast.Inspect(f, func(n ast.Node) bool {
				gd, ok := n.(*ast.GenDecl)
				if !ok || gd.Tok != token.CONST {
					return true
				}
				for _, spec := range gd.Specs {
					vs, ok := spec.(*ast.ValueSpec)
					if !ok {
						continue
					}
					for i, name := range vs.Names {
						if !name.IsExported() || !strings.HasPrefix(name.Name, "Kind") {
							continue
						}
						if seen[name.Name] {
							continue
						}
						seen[name.Name] = true
						kc := kindConst{ident: name.Name}
						if i < len(vs.Values) {
							if lit, ok := vs.Values[i].(*ast.BasicLit); ok {
								kc.value = lit.Value
							}
						}
						p.kind = append(p.kind, kc)
					}
				}
				return false
			})
		}
	}
	sort.Slice(p.kind, func(i, j int) bool { return p.kind[i].ident < p.kind[j].ident })
	return p, nil
}
