//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const modulePath = "xqdj/map"

func main() {
	src, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	formatted, err := format.Source(src)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile("all.go", formatted, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() ([]byte, error) {
	dirs, err := scanDirs(".")
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by go generate ./map; DO NOT EDIT.\n\n")
	b.WriteString("package 场地\n\n")
	if len(dirs) == 0 {
		return b.Bytes(), nil
	}
	b.WriteString("import (\n")
	for _, dir := range dirs {
		fmt.Fprintf(&b, "\t_ %q\n", modulePath+"/"+dir)
	}
	b.WriteString(")\n")
	return b.Bytes(), nil
}

func scanDirs(root string) ([]string, error) {
	ents, err := os.ReadDir(root)
	if err != nil {
		return nil, err
	}
	var dirs []string
	for _, e := range ents {
		if !e.IsDir() || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		ok, err := hasGo(filepath.Join(root, e.Name()))
		if err != nil {
			return nil, err
		}
		if ok {
			dirs = append(dirs, e.Name())
		}
	}
	sort.Strings(dirs)
	return dirs, nil
}

func hasGo(dir string) (bool, error) {
	ents, err := os.ReadDir(dir)
	if err != nil {
		return false, err
	}
	for _, e := range ents {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") && !strings.HasSuffix(e.Name(), "_test.go") {
			return true, nil
		}
	}
	return false, nil
}
